@echo off
echo Installing Backend Dependencies...
pip install -r backend\requirements.txt
echo Installing Frontend Dependencies...
cd frontend && npm install && cd ..
echo Starting Monorepo...
npm run dev
