import { useState, useEffect, useCallback } from 'react';
import { Download, Brain, FileText, Clock } from 'lucide-react';
import { useAppState } from '../context/AppContext';
import VolatilityTimeline, { VolatilityTimelineSkeleton } from '../components/Charts/VolatilityTimeline';
import SafetyWindow, { SafetyWindowSkeleton } from '../components/Charts/SafetyWindow';
import ImpactMetrics, { ImpactMetricsSkeleton } from '../components/Charts/ImpactMetrics';

// API response types
interface HistoricalPoint {
  timestamp: number;
  delta: number;
}

interface PredictedPoint {
  timestamp: number;
  delta: number;
  confidence: number;
}

interface AnalyticsData {
  historical: HistoricalPoint[];
  predicted: PredictedPoint[];
  accuracy: number;
}

// Mock API hook
function useAnalyticsData(locationId: string, range: string = '3h') {
  const [data, setData] = useState<AnalyticsData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchData = useCallback(async () => {
    setLoading(true);
    
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 800));
    
    // Generate mock data
    const now = Date.now();
    const historical: HistoricalPoint[] = [];
    const predicted: PredictedPoint[] = [];
    
    // Last 3 hours of historical data (every 2 minutes)
    for (let i = 90; i >= 0; i--) {
      const time = now - i * 2 * 60 * 1000;
      const baseValue = 0.25 + Math.sin(i * 0.1) * 0.15 + Math.cos(i * 0.05) * 0.1;
      const noise = (Math.random() - 0.5) * 0.08;
      historical.push({
        timestamp: time,
        delta: Math.max(0, Math.min(1, baseValue + noise)),
      });
    }
    
    // Next 40 minutes of predicted data (every 2 minutes)
    let lastValue = historical[historical.length - 1].delta;
    for (let i = 1; i <= 20; i++) {
      const time = now + i * 2 * 60 * 1000;
      const trend = Math.sin(i * 0.2) * 0.12;
      const predictedValue = Math.max(0, Math.min(1, lastValue + trend + (Math.random() - 0.5) * 0.04));
      const confidence = Math.max(0.6, 1 - i * 0.015);
      
      predicted.push({
        timestamp: time,
        delta: predictedValue,
        confidence,
      });
      
      lastValue = predictedValue;
    }
    
    setData({
      historical,
      predicted,
      accuracy: 98.4,
    });
    setLoading(false);
  }, [locationId, range]);

  useEffect(() => {
    fetchData();
    
    // Auto-refresh every 30 seconds
    const interval = setInterval(fetchData, 30000);
    return () => clearInterval(interval);
  }, [fetchData]);

  return { data, loading, error, refetch: fetchData };
}

// Generate PDF report (mock)
function generateReport(data: AnalyticsData, locationId: string): string {
  const now = new Date().toISOString();
  
  return `
CROWDSTATE AI - SYSTEMIC ANALYTICS REPORT
==========================================
Generated: ${now}
Location: ${locationId}
Time Range: Last 3 Hours + 40m Forecast

PREDICTION ACCURACY: ${data.accuracy.toFixed(1)}%

VOLATILITY METRICS
------------------
Historical Data Points: ${data.historical.length}
Forecast Data Points: ${data.predicted.length}
Current Volatility: ${data.historical[data.historical.length - 1].delta.toFixed(3)}
Predicted Peak: ${Math.max(...data.predicted.map(p => p.delta)).toFixed(3)}

ALERTS
------
No critical alerts in current window.

RECOMMENDATIONS
---------------
1. Monitor forecasted volatility peaks
2. Prepare AuraPath rerouting protocols
3. Maintain current sensor calibration

Report generated by CrowdState AI Analytics Engine
  `.trim();
}

export default function Analytics() {
  const { currentLocationId, stateData } = useAppState();
  const { data, loading } = useAnalyticsData(currentLocationId, '3h');
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = useCallback(() => {
    if (!data) return;
    
    setIsExporting(true);
    
    // Generate report
    const report = generateReport(data, currentLocationId);
    
    // Create download
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `crowdstate_analytics_${currentLocationId}_${new Date().toISOString().slice(0, 19)}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    setTimeout(() => setIsExporting(false), 1000);
  }, [data, currentLocationId]);

  const currentDelta = stateData?.delta ?? 0.21;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <h1 className="text-xs font-bold uppercase tracking-[0.2em] text-[#64748B]">
              Systemic Analytics
            </h1>
            <div className="flex items-center gap-1 px-2 py-0.5 bg-[#F0FDF4] rounded-full">
              <Brain size={12} className="text-[#10B981]" />
              <span className="text-[10px] font-bold text-[#10B981] uppercase">
                LSTM Active
              </span>
            </div>
          </div>
          
          <p className="text-2xl font-bold text-[#0F172A] font-helvetica">
            LSTM Predictive Science
          </p>
          
          <div className="flex items-center gap-4 mt-2">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 bg-[#F0FDF4] rounded-full text-[10px] font-bold text-[#10B981] uppercase tracking-wider">
              Prediction Accuracy: {data?.accuracy.toFixed(1) ?? '98.4'}%
            </span>
            
            <div className="flex items-center gap-1.5 text-xs text-[#64748B]">
              <Clock size={12} />
              <span>Updates every 30s</span>
            </div>
          </div>
        </div>

        {/* Export Button */}
        <button
          onClick={handleExport}
          disabled={isExporting || !data}
          className="flex items-center gap-2 px-4 py-2.5 bg-[#0F172A] text-white rounded-lg text-xs font-bold uppercase tracking-wider hover:bg-[#1E293B] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isExporting ? (
            <>
              <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Download size={16} />
              Export Analysis Report
            </>
          )}
        </button>
      </div>

      {/* Impact Metrics Row */}
      {loading ? (
        <ImpactMetricsSkeleton />
      ) : (
        <ImpactMetrics
          recoveredCapacity="14.2%"
          congestionAvoided="84k"
          systemicUptime="99.98%"
        />
      )}

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-6">
        {/* Left Column - Volatility Chart */}
        <div>
          {loading ? (
            <VolatilityTimelineSkeleton />
          ) : (
            <VolatilityTimeline
              historicalData={data?.historical ?? []}
              predictedData={data?.predicted ?? []}
              predictionAccuracy={data?.accuracy}
            />
          )}
        </div>

        {/* Right Column - Safety Window */}
        <div>
          {loading ? (
            <SafetyWindowSkeleton />
          ) : (
            <SafetyWindow
              initialSeconds={180}
              volatility={currentDelta}
            />
          )}
        </div>
      </div>

      {/* Additional Info Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Model Info */}
        <div className="bg-white rounded-xl border border-[#E2E8F0] p-5 shadow-sm">
          <div className="flex items-center gap-2 mb-3">
            <Brain size={16} className="text-[#0D9488]" />
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#64748B]">
              LSTM Model
            </h3>
          </div>
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-[#64748B]">Architecture</span>
              <span className="font-mono text-[#0F172A]">2-Layer BiLSTM</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#64748B]">Sequence Length</span>
              <span className="font-mono text-[#0F172A]">60 timesteps</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#64748B]">Hidden Units</span>
              <span className="font-mono text-[#0F172A]">128</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#64748B]">Dropout</span>
              <span className="font-mono text-[#0F172A]">0.2</span>
            </div>
          </div>
        </div>

        {/* Data Sources */}
        <div className="bg-white rounded-xl border border-[#E2E8F0] p-5 shadow-sm">
          <div className="flex items-center gap-2 mb-3">
            <FileText size={16} className="text-[#0D9488]" />
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#64748B]">
              Data Sources
            </h3>
          </div>
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-[#64748B]">Video Feeds</span>
              <span className="font-mono text-[#0F172A]">4 Active</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#64748B]">Audio Sensors</span>
              <span className="font-mono text-[#0F172A]">8 Active</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#64748B]">Sample Rate</span>
              <span className="font-mono text-[#0F172A]">2 FPS</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#64748B]">Buffer Size</span>
              <span className="font-mono text-[#0F172A]">5s Window</span>
            </div>
          </div>
        </div>

        {/* Performance Stats */}
        <div className="bg-white rounded-xl border border-[#E2E8F0] p-5 shadow-sm">
          <div className="flex items-center gap-2 mb-3">
            <Clock size={16} className="text-[#0D9488]" />
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#64748B]">
              Performance
            </h3>
          </div>
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-[#64748B]">Inference Time</span>
              <span className="font-mono text-[#0F172A]">156ms</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#64748B]">Throughput</span>
              <span className="font-mono text-[#0F172A]">6.4 FPS</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#64748B]">Latency</span>
              <span className="font-mono text-[#0F172A]">12ms</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#64748B]">GPU Util</span>
              <span className="font-mono text-[#0F172A]">42%</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
